// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: languages.sql

package database

import (
	"context"
)

const addLanguage = `-- name: AddLanguage :exec
INSERT INTO languages (code, name)
VALUES (
    ?1,
    ?2
)
`

type AddLanguageParams struct {
	Code string
	Name string
}

func (q *Queries) AddLanguage(ctx context.Context, arg AddLanguageParams) error {
	_, err := q.db.ExecContext(ctx, addLanguage, arg.Code, arg.Name)
	return err
}
