// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package database

import (
	"database/sql"
	"time"
)

type Company struct {
	ID          int64
	NameKey     string
	WebsiteUrl  sql.NullString
	LocationKey sql.NullString
}

type Contact struct {
	ID       int64
	Type     string
	LabelKey string
	Value    string
}

type Language struct {
	ID   int64
	Code string
	Name string
}

type Position struct {
	ID          int64
	CompanyID   int64
	TitleKey    string
	StartDate   time.Time
	EndDate     sql.NullTime
	Description sql.NullString
}

type PositionItem struct {
	ID         int64
	PositionID int64
	ItemKey    string
}

type Profile struct {
	ID       int64
	Name     string
	TitleKey string
	AboutKey string
	ImageUrl sql.NullString
}

type Project struct {
	ID       int64
	TitleKey string
	DescKey  string
}

type Translation struct {
	ID         int64
	Key        string
	LanguageID int64
	Text       string
}
