name: Deploy Static Files

on:
  push:
    branches:
      - main
    paths:
      - 'static/**'
      - '.github/workflows/static.yml'

jobs:
  deploy-static:
    runs-on: ubuntu-latest

    env:
      DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
      DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
      DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
      DEPLOY_PORT: ${{ secrets.DEPLOY_SSH_PORT || 22 }}
      DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Upload static files
        uses: appleboy/scp-action@v1
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          source: "static"
          target: ${{ env.DEPLOY_PATH }}/static

      - name: SSH to server (stub)
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ env.DEPLOY_HOST }}
          username: ${{ env.DEPLOY_USER }}
          key: ${{ env.DEPLOY_KEY }}
          port: ${{ env.DEPLOY_PORT }}
          script: |
            echo "Static files deployed. No restart needed."

